### PR TITLE
Feature/#41 - Updated NUnit tests to use new NUnit pattern

### PR DESCRIPTION
**Pull request by AtwoodTM**
The NUnit tests had been using the deprecated Assert.AreEqual.  These have been changed to the new Assert.That pattern....

### CODE REVIEW

**Comment by AtwoodTM** [comment]
The PR was submitted two weeks ago with no response.  Is this project still alive @jbtule?  If not, we will use our fork to progress development for FSharp.Interop.Dynamic.

**Comment by jbtule** [comment]
It's still alive in that it's critical to our business, but not really under active development for new features. With reformatting of every file, this PR involves a lot more scrutiny than a PR described as updating the unit tests asset method.

**Comment by AtwoodTM** [comment]
It's critical to the business running a deprecated version of .NET with security vulnerabilities?  That's not a concern?  Forking and creating a new version that will be secure from an app vulnerability perspective.

**Comment by jbtule** [comment]
Go ahead. it's built with .net std 2.0, so no app vulnerabilities issues, it will link with .net 8.0 or whatever. and .net 4.8.1 has no end of support date. Like I said not take pull request making 11K line changes.

**Pull request closed without merging**
