### PR TITLE
.NET Core version

### PR DESCRIPTION
**Pull request by HamedFathi**
I added .NET Core version

### CODE REVIEW

**Comment by jbtule** [comment]
Having a separate namespace for .net core isn't ideal. #if defs are typically the way to go. I'll probably let this sit here until I have time to port it. Unless you want to work on this PR some more, including cross compiling and unit tests.

**Comment by HamedFathi** [comment]
Can we use Preprocessor Directives  like #if in .NET Core project for .NET Framework project or visa versa ? I think because of we have different assemblies for two separate frameworks we need to have new branch and namespace . Am I right?

**Comment by jbtule** [comment]
Yes, both .net core and .net framework can use preprocessor directives. If we don't lose any features, the core just becomes the newest forward compatible binary of dynamitey, and others are just compiled to work with previous .net framework for compatibility sake.  

A namespace change breaks easy porting for others and makes libraries that depend on dynamitey problematic porting wise to say the least.

https://docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries

**Comment by jbtule** [comment]
Replaced with #16

**Pull request closed without merging**
